modLoader="javafml"
loaderVersion="[39,)"
#issueTrackerURL="http://my.issue.tracker/" #TODO: Endercore REPO
license="CC0"

[[mods]]
modId="endercore"
version="${file.jarVersion}"
displayName="EnderCore"
#updateJSONURL="http://ci.tterrag.com/job/EnderCore"
displayURL="http://enderio.com"
logoFile="examplemod.png"
credits=""
authors="tterrag, CrazyPants, HenryLoenwind, Rover656, HypherionSA"
description="Library mod used by EnderIO, EnderZoo, and others"

[[dependencies.endercore]]
modId="minecraft"
mandatory=true
versionRange="1.18.1"
side="BOTH"

[[dependencies.endercore]]
modId="forge"
mandatory=true
versionRange="39.0.5"
side="BOTH"
